import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

/// Displays the 60-digit numeric security code for the current E2EE session
/// with a contact. The code can be compared via QR code scanning using
/// `mobile_scanner`.
///
/// Requirements: 9.5
class SecurityCodeScreen extends ConsumerWidget {
  const SecurityCodeScreen({
    super.key,
    required this.contactName,
  });

  final String contactName;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    // In production, the security code is generated by EncryptionService
    // from the shared secret. For now, we show a placeholder.
    final securityCode = _generatePlaceholderCode();

    return Scaffold(
      appBar: AppBar(
        title: Text('Security code'),
        actions: [
          IconButton(
            icon: const Icon(Icons.qr_code_scanner),
            tooltip: 'Scan QR code',
            onPressed: () {
              ScaffoldMessenger.of(context).showSnackBar(
                const SnackBar(
                  content: Text('QR scanning not yet implemented'),
                ),
              );
            },
          ),
        ],
      ),
      body: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          const SizedBox(height: 16),

          // ── Info text ─────────────────────────────────────────
          Text(
            'Verify $contactName\'s security code to confirm that '
            'your messages and calls are end-to-end encrypted.',
            style: Theme.of(context).textTheme.bodyMedium?.copyWith(
              color: Theme.of(context).colorScheme.outline,
            ),
            textAlign: TextAlign.center,
          ),

          const SizedBox(height: 32),

          // ── QR Code placeholder ───────────────────────────────
          Center(
            child: Container(
              width: 200,
              height: 200,
              decoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.circular(12),
                border: Border.all(
                  color: Theme.of(context).colorScheme.outlineVariant,
                ),
              ),
              child: Center(
                child: Icon(
                  Icons.qr_code,
                  size: 120,
                  color: Theme.of(context).colorScheme.primary,
                ),
              ),
            ),
          ),

          const SizedBox(height: 32),

          // ── 60-digit code ─────────────────────────────────────
          Text(
            'You can also compare this number with $contactName\'s '
            'device to verify the security code:',
            style: Theme.of(context).textTheme.bodySmall?.copyWith(
              color: Theme.of(context).colorScheme.outline,
            ),
            textAlign: TextAlign.center,
          ),

          const SizedBox(height: 16),

          // Display the code in a 12x5 grid
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: Theme.of(context).colorScheme.surfaceContainerHighest,
              borderRadius: BorderRadius.circular(12),
            ),
            child: Column(
              children: _buildCodeGrid(context, securityCode),
            ),
          ),

          const SizedBox(height: 24),

          // ── Verification status ───────────────────────────────
          Card(
            child: Padding(
              padding: const EdgeInsets.all(16),
              child: Row(
                children: [
                  const Icon(Icons.check_circle, color: Colors.green),
                  const SizedBox(width: 12),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const Text(
                          'Key verified',
                          style: TextStyle(fontWeight: FontWeight.w500),
                        ),
                        Text(
                          'You\'ve verified $contactName\'s device.',
                          style: Theme.of(context).textTheme.bodySmall,
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }

  List<Widget> _buildCodeGrid(BuildContext context, String code) {
    final widgets = <Widget>[];
    // Arrange in rows of 12 digits (5 rows of 12 = 60)
    for (var row = 0; row < 5; row++) {
      final rowDigits = <Widget>[];
      for (var col = 0; col < 12; col++) {
        final index = row * 12 + col;
        if (index < code.length) {
          rowDigits.add(
            SizedBox(
              width: 28,
              child: Text(
                code[index],
                style: const TextStyle(
                  fontSize: 16,
                  fontFamily: 'monospace',
                  fontWeight: FontWeight.w500,
                ),
                textAlign: TextAlign.center,
              ),
            ),
          );
        }
      }
      widgets.add(
        Padding(
          padding: const EdgeInsets.symmetric(vertical: 2),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              ...rowDigits.sublist(0, 4),
              const SizedBox(width: 8),
              ...rowDigits.sublist(4, 8),
              const SizedBox(width: 8),
              ...rowDigits.sublist(8),
            ],
          ),
        ),
      );
    }
    return widgets;
  }

  String _generatePlaceholderCode() {
    // In production, generated from EncryptionService.verifySecurityCode()
    return '1234 5678 9012 3456 7890 1234 5678 9012 3456 7890 1234 5678 9012 3456 7890';
  }
}